version: 3.0.0

services:
  mongodb:
    container_name: boilerplate-database
    image: mongo:7.0-jammy
    restart: always
    networks:
      - mongodb-net
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017

  server:
    container_name: boilerplate-api
    build:
      context: .
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
    env_file:
      - .env
    networks:
      - mongodb-net
    ports:
      - 3000:3000

networks:
  mongodb-net:

volumes:
  mongodb:
