version: 3.0.0

services:
  mongodb:
    container_name: database
    image: mongo:7.0-jammy
    restart: always
    networks:
      - mongodb-net
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - redis:/data/cache
    ports:
      - 6379:6379

  server:
    container_name: server
    build:
      context: .
    depends_on:
      - mongodb
      - redis
    environment:
      NODE_ENV: development
    env_file:
      - .env
    networks:
      - mongodb-net
    ports:
      - 3000:3000

networks:
  mongodb-net:

volumes:
  mongodb:
  redis:
